[package]
name = "gesetze_im_internet"
version = "0.1.0"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]
edition = "2018"

[dependencies]
reqwest = "0.9.17"
serde = "1.0.91"
serde-xml-rs = "0.3.1"
zip = "0.5"
regex = "1"
clap = "~2.27.0"
lazy_static = "0.1.*"
log = "0.4"
stderrlog = "0.4"
